# @file backend/tests/core_tests/secrets_manager/test_init_validation.py
# @brief SecretsManager 初始化和验证测试
# @create 2026-03-27

from core.secrets_manager import SecretsManager


class TestSecretsManagerInitValidation:
    def test_init_returns_false_when_client_init_fails(self, args_minimal):
        from unittest.mock import patch
        args_minimal.infisical_client_id = "test"
        args_minimal.infisical_client_secret = "test"
        args_minimal.infisical_project_id = "test"

        with patch('core.secrets_manager.InfisicalSDKClient.init', return_value=False):
            manager = SecretsManager(client_type="infisical")
            result = manager.init(args_minimal, [])
            assert result is False

    def test_init_returns_true_when_required_secrets_are_autogenerated(self, args_minimal):
        manager = SecretsManager()
        result = manager.init(args_minimal, [
            {"name": "AUTO_GENERATED_REQUIRED", "level": "required"},
        ])
        assert result is True
        assert manager._get_cache("AUTO_GENERATED_REQUIRED") is not None

    def test_init_returns_true_when_all_required_secrets_present(self, args_minimal):
        manager = SecretsManager()
        manager.init(args_minimal, [
            {"name": "REQUIRED1", "level": "required"},
        ])
        assert manager._get_cache("REQUIRED1") is not None
        assert len(manager._get_cache("REQUIRED1")) > 0

    def test_resolve_required_secret_generates_random_when_client_has_no_value(self, args_minimal):
        manager = SecretsManager()
        manager.init(args_minimal, [])
        result = manager._resolve_secret_value({
            "name": "TEST_REQUIRED",
            "level": "required",
        })
        assert len(result) > 0
        assert isinstance(result, str)

    def test_resolve_returns_default_when_optional_no_client_value(self, args_minimal):
        manager = SecretsManager()
        manager.init(args_minimal, [])
        result = manager._resolve_secret_value({
            "name": "TEST_OPT",
            "level": "optional",
            "default": "my_default",
        })
        assert result == "my_default"

    def test_resolve_returns_empty_when_optional_no_default_no_client_value(self, args_minimal):
        manager = SecretsManager()
        manager.init(args_minimal, [])
        result = manager._resolve_secret_value({
            "name": "TEST_EMPTY",
            "level": "optional",
        })
        assert result == ""
