import type { ThemeConfig } from 'antd';

export const harvestFlowGradient = 'linear-gradient(135deg, #2563EB 0%, #F59E0B 100%)';

export const flowDesignToken = {
  colorPrimary: '#2563EB',
  colorSuccess: '#10B981',
  colorWarning: '#F59E0B',
  colorError: '#EF4444',
  colorInfo: '#3B82F6',
  borderRadius: 6,
  borderRadiusSM: 6,
  borderRadiusLG: 12,
  borderRadiusXS: 8,
  borderRadiusOuter: 12,
  fontFamily: 'Inter, PingFang SC, Microsoft YaHei, sans-serif',
  fontSize: 14,
  fontSizeHeading1: 24,
  fontSizeHeading2: 20,
  fontSizeHeading3: 18,
  fontSizeHeading4: 16,
  fontSizeHeading5: 14,
  lineHeight: 1.5,
  lineHeightHeading1: 1.3,
  lineHeightHeading2: 1.3,
  lineHeightHeading3: 1.3,
  lineHeightHeading4: 1.3,
  lineHeightHeading5: 1.3,
  controlHeight: 40,
  controlHeightSM: 32,
  controlHeightXS: 24,
  controlHeightLG: 48,
  marginXS: 4,
  marginSM: 8,
  margin: 16,
  marginMD: 20,
  marginLG: 24,
  marginXL: 32,
  marginXXL: 48,
  paddingXS: 4,
  paddingSM: 8,
  padding: 16,
  paddingMD: 20,
  paddingLG: 24,
  paddingXL: 32,
  boxShadow: '0 1px 3px rgba(0,0,0,0.08), 0 1px 2px rgba(0,0,0,0.04)',
  boxShadowSecondary: '0 4px 6px rgba(0,0,0,0.08), 0 2px 4px rgba(0,0,0,0.04)',
  boxShadowTertiary: '0 10px 15px rgba(0,0,0,0.1), 0 4px 6px rgba(0,0,0,0.05)',
  colorBgContainer: '#FFFFFF',
  colorBgElevated: '#FFFFFF',
  colorBgLayout: '#F8FAFC',
  colorBgSpotlight: '#F1F5F9',
  colorText: '#334155',
  colorTextSecondary: '#64748B',
  colorTextTertiary: '#94A3B8',
  colorTextQuaternary: '#CBD5E1',
  colorTextHeading: '#0F172A',
  colorBorder: '#E2E8F0',
  colorBorderSecondary: '#F1F5F9',
  colorFill: '#F1F5F9',
  colorFillSecondary: '#E2E8F0',
  colorFillTertiary: '#CBD5E1',
  colorFillQuaternary: '#F8FAFC',
};

export const harvestFlowTheme: ThemeConfig = {
  token: flowDesignToken,
  components: {
    Button: {
      borderRadius: 6,
      controlHeight: 40,
      controlHeightSM: 32,
      controlHeightLG: 48,
      colorPrimary: '#2563EB',
      colorPrimaryHover: '#1D4ED8',
      colorPrimaryActive: '#1E40AF',
    },
    Card: {
      borderRadiusLG: 12,
      paddingLG: 24,
      boxShadow: '0 1px 3px rgba(0,0,0,0.08), 0 1px 2px rgba(0,0,0,0.04)',
    },
    Input: {
      borderRadius: 6,
      controlHeight: 40,
      controlHeightSM: 32,
      controlHeightLG: 48,
    },
    Select: {
      borderRadius: 6,
      controlHeight: 40,
      controlHeightSM: 32,
      controlHeightLG: 48,
    },
    Table: {
      borderRadiusLG: 12,
      headerBg: '#F8FAFC',
      rowHoverBg: '#F8FAFC',
      padding: 16,
      paddingMD: 16,
      cellPaddingBlock: 16,
      cellPaddingInline: 16,
    },
    Menu: {
      itemHeight: 48,
      itemMarginInline: 8,
      itemBorderRadius: 8,
      itemPaddingInline: 16,
    },
    Layout: {
      headerBg: '#FFFFFF',
      siderBg: '#1E293B',
      bodyBg: '#F8FAFC',
    },
    Tag: {
      borderRadius: 9999,
    },
    Modal: {
      borderRadiusLG: 12,
    },
    Drawer: {
      borderRadiusLG: 12,
    },
    Badge: {
      borderRadius: 9999,
    },
  },
};
