import type { ThemeConfig } from 'antd';

export const flowPalette = {
  primary: '#2563EB',
  primaryHover: '#1D4ED8',
  primaryActive: '#1E40AF',
  success: '#10B981',
  warning: '#F59E0B',
  error: '#EF4444',
  info: '#3B82F6',
  purple: '#8B5CF6',
  slate900: '#0F172A',
  slate800: '#1E293B',
  slate500: '#64748B',
  slate400: '#94A3B8',
  slate200: '#E2E8F0',
  slate100: '#F1F5F9',
  slate50: '#F8FAFC',
  white: '#FFFFFF',
};

export const statusPalette: Record<string, string> = {
  raw: flowPalette.slate400,
  curated: flowPalette.primary,
  approved: flowPalette.success,
  rejected: flowPalette.error,
};

export const scorePalette = [flowPalette.error, flowPalette.warning, flowPalette.warning, flowPalette.success, flowPalette.success];

export const flowDesignToken = {
  colorPrimary: flowPalette.primary,
  colorSuccess: flowPalette.success,
  colorWarning: flowPalette.warning,
  colorError: flowPalette.error,
  colorInfo: flowPalette.info,
  borderRadius: 8,
  borderRadiusSM: 6,
  borderRadiusLG: 12,
  borderRadiusXS: 6,
  borderRadiusOuter: 12,
  fontFamily: 'Inter, PingFang SC, Microsoft YaHei, sans-serif',
  fontSize: 14,
  fontSizeHeading1: 24,
  fontSizeHeading2: 20,
  fontSizeHeading3: 18,
  fontSizeHeading4: 16,
  fontSizeHeading5: 14,
  lineHeight: 1.6,
  lineHeightHeading1: 1.4,
  lineHeightHeading2: 1.4,
  lineHeightHeading3: 1.4,
  lineHeightHeading4: 1.4,
  lineHeightHeading5: 1.4,
  controlHeight: 36,
  controlHeightSM: 28,
  controlHeightXS: 22,
  controlHeightLG: 44,
  marginXS: 4,
  marginSM: 8,
  margin: 16,
  marginMD: 20,
  marginLG: 24,
  marginXL: 32,
  marginXXL: 48,
  paddingXS: 4,
  paddingSM: 8,
  padding: 16,
  paddingMD: 20,
  paddingLG: 24,
  paddingXL: 32,
  boxShadow: '0 1px 3px rgba(15,23,42,0.06), 0 1px 2px rgba(15,23,42,0.04)',
  boxShadowSecondary: '0 4px 6px rgba(15,23,42,0.06), 0 2px 4px rgba(15,23,42,0.04)',
  boxShadowTertiary: '0 10px 15px rgba(15,23,42,0.08), 0 4px 6px rgba(15,23,42,0.04)',
  colorBgContainer: flowPalette.white,
  colorBgElevated: flowPalette.white,
  colorBgLayout: flowPalette.slate50,
  colorBgSpotlight: flowPalette.slate100,
  colorText: '#334155',
  colorTextSecondary: flowPalette.slate500,
  colorTextTertiary: flowPalette.slate400,
  colorTextQuaternary: '#CBD5E1',
  colorTextHeading: flowPalette.slate900,
  colorBorder: flowPalette.slate200,
  colorBorderSecondary: flowPalette.slate100,
  colorFill: flowPalette.slate100,
  colorFillSecondary: flowPalette.slate200,
  colorFillTertiary: '#CBD5E1',
  colorFillQuaternary: flowPalette.slate50,
};

export const harvestFlowTheme: ThemeConfig = {
  token: flowDesignToken,
  components: {
    Button: {
      borderRadius: 8,
      controlHeight: 36,
      controlHeightSM: 28,
      controlHeightLG: 44,
      colorPrimaryHover: flowPalette.primaryHover,
      colorPrimaryActive: flowPalette.primaryActive,
      primaryShadow: 'none',
      defaultShadow: 'none',
      dangerShadow: 'none',
    },
    Card: {
      borderRadiusLG: 12,
      paddingLG: 24,
      boxShadowTertiary: '0 1px 3px rgba(15,23,42,0.06), 0 1px 2px rgba(15,23,42,0.04)',
    },
    Table: {
      headerBg: flowPalette.slate50,
      headerColor: '#475569',
      rowHoverBg: flowPalette.slate50,
      borderColor: flowPalette.slate100,
      cellPaddingBlock: 14,
      cellPaddingInline: 16,
    },
    Menu: {
      itemHeight: 44,
      itemMarginInline: 8,
      itemBorderRadius: 8,
      itemPaddingInline: 12,
    },
    Layout: {
      headerBg: flowPalette.white,
      siderBg: flowPalette.slate900,
      bodyBg: flowPalette.slate50,
      headerHeight: 56,
    },
    Tag: {
      borderRadius: 999,
    },
    Modal: {
      borderRadiusLG: 12,
    },
    Drawer: {
      borderRadiusLG: 12,
    },
    Badge: {
      borderRadius: 999,
    },
    Descriptions: {
      itemPaddingBottom: 12,
    },
    Segmented: {
      itemSelectedBg: flowPalette.white,
      trackBg: flowPalette.slate100,
    },
    Tabs: {
      titleFontSize: 14,
    },
  },
};
